### ISSUE TITLE
Camera intrinsics?

### ISSUE THREAD

**Issue by Yuliang-Zou** [amir32002/3D_Street_View#3]
Hi, thanks for sharing this dataset! I wonder if the camera intrinsic parameters are also included.

**Comment by amir32002** [comment]
The focal length was a fixed value. Also, note that the images are pinhole projections from an equirectangular image. @Tilman1110 can advise further if more questions arise.

**Comment by Tilman1110** [comment]
There is an (empirically found) relation between the zoom level and the FOV:

if (zoom <= 2)
		return 126.5 - zoom * 36.75;
	else
		return 195.93 / pow(1.92, zoom);

We use a zoom level of 1 and the original resolution is always 640x640. 
I hope this helps. Let me know if you need further information.

**Comment by Tilman1110** [comment]
So, the FOV should be 89.75 @ 640x640 pixel

**Comment by Yuliang-Zou** [comment]
Hi @Tilman1110 @amir32002 , thank you so much! 

Since I need the camera intrinsics, I wonder how to know the principal point offset x_0 and y_0? And can I assume the axis skew s=0?

**Comment by Tilman1110** [comment]
good point. we do not have an instrinsic calibration and the images are projections (virtual cameras) of a spherical image that is again probably stitched together from the Google car camera images. so the individual images have probably been undistorted. Just assume the princ point to be in the image center. all other intrinsic parameters should be set to zero or identity.

 if you need further help with setting up the camera transformations let me know. I'm very happy to help.

**Comment by Yuliang-Zou** [comment]
Thank you!
